##
 #
 # @Author Rizki Mufrizal <mufrizalrizki@gmail.com>
 # @Since Feb 14, 2016
 # @Time 12:43:27 AM
 # @Encoding ISO-8859-1
 # @Project Aplikasi-Absensi-Server
 # @Package Expression package is undefined on line 8, column 15 in Templates/Other/properties.properties.
 # 
 ##

# spring datasource jpa
spring: 
    datasource: 
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/absensi?autoReconnect=true
        username: root
        password: root
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000
    
    # spring hibernate    
    jpa: 
        generate-ddl: true
        show-sql: true
        properties: 
            hibernate: 
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect

    # jackson config
    jackson: 
        serialization: 
            indent_output: true

    # spring data rest config
    data: 
        rest: 
            basePath: /api

    # spring devtools
    devtools: 
        livereload: 
            enabled: true

    # spring redis
    redis: 
        host: 127.0.0.1
        port: 6379

    # spring thymeleaf
    thymeleaf: 
        cache: false

# tomcat konfiguration
server: 
    tomcat: 
        access_log_enabled: true
        basedir: target/tomcat