##
 #
 # @Author Rizki Mufrizal <mufrizalrizki@gmail.com>
 # @Since Feb 22, 2016
 # @Time 6:45:37 PM
 # @Encoding ISO-8859-1
 # @Project Aplikasi-Absensi-Server
 # @Package Expression package is undefined on line 8, column 15 in Templates/Other/properties.properties.
 # 
 ##
 
 spring:
    profiles:
        active: openshift
    
    datasource: 
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}?autoReconnect=true
        username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
        password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000
    
    # spring hibernate    
    jpa: 
        generate-ddl: true
        show-sql: true
        properties: 
            hibernate: 
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect

    # jackson config
    jackson: 
        serialization: 
            indent_output: true

    # spring data rest config
    data: 
        rest: 
            basePath: /api
    
    # spring redis
    redis: 
        host: pub-redis-16033.us-east-1-3.6.ec2.redislabs.com
        port: 16033
        password: 12345

    # spring thymeleaf
    thymeleaf: 
        cache: false